#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
name: Main Build Orchestrator

on:
  push:
    branches: [main]

jobs:

  set-build-properties:
    # Use the version.properties file to source the galasa-version output variable.
    # This variable can be referenced by other jobs in this flow using 
    # ${{ needs.set-build-properties.outputs.galasa-version }}
    runs-on: ubuntu-latest
    outputs:
      galasa-version: ${{ steps.set-build-properties.outputs.GALASA_VERSION }}
    steps:
      - id: checkout-code
        uses: actions/checkout@v4 
        with:
          sparse-checkout: |
            build.properties
          sparse-checkout-cone-mode: false

      - id: set-build-properties
        run: |
          cat build.properties | grep "=" >> $GITHUB_OUTPUT

  check-required-secrets-configured:
    name: Check required secrets configured
    uses: galasa-dev/galasa/.github/workflows/check-required-secrets-configured.yaml@main
    with:
      check_write_github_packages_username: 'true'
      check_write_github_packages_token: 'true'
      check_maven_settings_xml: 'true'
      check_gpg_key: 'true'
      check_gpg_keyid: 'true'
      check_gpg_passphrase: 'true'
    secrets:
      WRITE_GITHUB_PACKAGES_USERNAME: ${{ secrets.WRITE_GITHUB_PACKAGES_USERNAME }}
      WRITE_GITHUB_PACKAGES_TOKEN: ${{ secrets.WRITE_GITHUB_PACKAGES_TOKEN }}
      MAVEN_SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_KEYID: ${{ secrets.GPG_KEYID }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  build-platform:
    name: Build the 'platform' module
    needs: [check-required-secrets-configured]
    uses: ./.github/workflows/platform.yaml
    secrets: inherit

  build-buildutils:
    name: Build the 'buildutils' module
    needs: [check-required-secrets-configured]
    uses: ./.github/workflows/buildutils.yaml
    secrets: inherit

  build-wrapping:
    name: Build the 'wrapping' module
    needs: [build-platform]
    uses: ./.github/workflows/wrapping.yaml
    secrets: inherit

  build-gradle:
    name: Build the 'gradle' module
    needs: [build-platform]
    uses: ./.github/workflows/gradle.yaml
    secrets: inherit

  build-maven:
    name: Build the 'maven' module
    needs: [build-gradle]
    uses: ./.github/workflows/maven.yaml
    secrets: inherit

  build-framework:
    name: Build the 'framework' module
    needs: [build-buildutils, build-wrapping, build-maven]
    uses: ./.github/workflows/framework.yaml
    secrets: inherit

  build-extensions:
    name: Build the 'extensions' module
    needs: [build-framework]
    uses: ./.github/workflows/extensions.yaml
    secrets: inherit

  build-managers:
    name: Build the 'managers' module
    needs: [build-framework]
    uses: ./.github/workflows/managers.yaml
    secrets: inherit

  build-obr:
    name: Build the 'obr' module
    needs: [build-extensions, build-managers, set-build-properties ]
    uses: ./.github/workflows/obr.yaml
    secrets: inherit
    with:
      galasa-version: "${{ needs.set-build-properties.outputs.galasa-version }}"
